### ISSUE TITLE
RSS config

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/irlpodcast#111]
A Mozilla volunteer wrote to me with this: "One small thing I have noticed is when I select to subscribe to the RSS feed, I am taken to https://feeds.mozilla-podcasts.org/irl, which does not allow me to subscribe using the RSS tool built into Firefox ("Live Bookmarks"), but if the page was coded differently, I would see something like http://feeds.bbci.co.uk/news/world/europe/rss.xml.  A small thing (I have subscribed instead using Thunderbird), but something to maybe think about changing."

**Comment by stephaniehobson** [comment]
@jpetto Do you have any history on mozilla-podcasts.org?

**Comment by jpetto** [comment]
`https://feeds.mozilla-podcasts.org/` is a CNAME to `redirect.feedpress.me`, which handles our RSS feed (and gives us analytics). We may be able to work with them to improve the experience/enable Live Bookmarking. I would say best place to start is asking `@misener` in `#ih-podcast` on Slack.

**Comment by stephaniehobson** [comment]
Firefox is [removing product support for RSS feeds](https://www.gijsk.com/blog/2018/10/firefox-removes-core-product-support-for-rss-atom-feeds/). I'm going to close this issue.
