### ISSUE TITLE
Add footer item - Creative Commons license

### ISSUE THREAD

**Issue by ejregithub** [mozilla/irlpodcast#124]
https://bugzilla.mozilla.org/show_bug.cgi?id=1469401

Success Criteria
- [x] Add Creative Commons license
- [x] Link to license details
- [x] In footer of every page

**Comment by ejregithub** [comment]
@stephaniehobson - I've asked for requirements from Michaela in the bug above and will add the Success Criteria when those are made clear.

**Comment by stephaniehobson** [comment]
Here's what I've got:

<img width="1034" alt="screen shot 2018-09-06 at 10 50 05 am" src="https://user-images.githubusercontent.com/854701/45175610-b1d38000-b1c2-11e8-8553-469f484abff2.png">
