### ISSUE TITLE
[11/12] Season 4 Trailer

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/irlpodcast#141]
[Season 4 Trailer](https://bugzilla.mozilla.org/show_bug.cgi?id=1504848)

**Comment by stephaniehobson** [comment]
https://irlpodcast.org/season4/trailer

**Comment by stephaniehobson** [comment]
See #144 

Episode is merged and ready to go on Monday at 6am.

**Comment by ejregithub** [comment]
Jon Petto pushed this, closing
