### ISSUE TITLE
"Listen with radiopublic" badge is broken/unreadable, depending on your system fonts.

### ISSUE THREAD

**Issue by dholbert** [mozilla/irlpodcast#170]
Here's how the "Listen with RadioPublic" badge at https://irlpodcast.org/season4/episode5/ looks for me:

![selection_051](https://user-images.githubusercontent.com/426803/52451431-d629e480-2af3-11e9-9be5-13e1c9b29666.png)

If you look at the image's source, you can see that it's doing some bespoke text placement while assuming (incorrectly) that it's rendered in a particular font with extremely specific character placement:
```

        <text transform="translate(31 9)">
          <tspan x="0" y="14">RadioPubli</tspan>
        </text>
        <text transform="translate(31 9)">
          <tspan x="67.028" y="14">c</tspan>
```

We shouldn't be using this badge. I found a better (?) one at https://spotlight.radiopublic.com/images/radiopublic-button-assets/radiopublic-button-white-full-color%401x.svg that looks better -- it uses `<path>` so that it doesn't make any assumptions about fonts.  It's got a dark border, but you can get rid of that (to match the look of our site) by hand-editing it to remove its first `<rect>`.

(The `<path>`-for-text solution is worse for accessibility, but we can get around that by including alt text, I think, which we already do -- great!)

**Comment by dholbert** [comment]
(I'm on Ubuntu Linux using Firefox Nightly, for what it's worth.)

**Comment by stephaniehobson** [comment]
@dholbert If you have a moment before Thursday this week could you please look on [our dev server](https://dev.irlpodcast.org/) and see if the new SVG is displaying properly for you? Thanks!

**Comment by dholbert** [comment]
Yup, looks better - thanks!

Here's a screenshot -- current site on top, dev server on bottom:
![image](https://user-images.githubusercontent.com/426803/53393134-64a1c100-3950-11e9-9a8a-d7c117588e28.png)

**Comment by stephaniehobson** [comment]
Awesome, thanks! And thank you for the very details issue complete with solution :)

It should be updated on the site when we publish the episode Monday (if it doesn't go earlier).
