### ISSUE TITLE
Add CSS/JS linter

### ISSUE THREAD

**Issue by jpetto** [mozilla/irlpodcast#22]

**Comment by Rupeshiya** [comment]
@jpetto  I would like to give it a try ?

**Comment by jpetto** [comment]
@Rupeshiya - Feel free. Thanks!

**Comment by Rupeshiya** [comment]
@jpetto  can you please explain ,what should I do ,since I have never used linter till now ??

**Comment by jpetto** [comment]
I would start by checking out [gulp-eslint](https://github.com/adametry/gulp-eslint) and [gulp-stylelint](https://github.com/olegskl/gulp-stylelint), then use [mozilla.org's gulpfile](https://github.com/mozilla/bedrock/blob/master/gulpfile.js) as a guide. (There's quite a bit going on in that gulp file, but just focus on the lint stuff for this task.)

Let me know if you get stuck!

**Comment by stephaniehobson** [comment]
Fixed in #160
