### ISSUE TITLE
QA site for initial launch

### ISSUE THREAD

**Issue by jpetto** [mozilla/irlpodcast#3]
@craigcook & @alexgibson -

For initial release, I think it best to focus on:

- Rendering in major browsers, focusing on mobile first
- Subscribe functionality (knowing Spotify link is yet to come)
- Embed player functionality
- Share functionality
- Newsletter functionality
- Code quality/performance

Dev URL is: https://mozilla.github.io/irlpodcast

I tested in old IE's today, and they are good enough to let a user click a subscribe link. SVGs are obviously not visible, which is probably the biggest issue.

Also, suggestions on commit history? Thinking I should just rebase the entire log down to a single `initial release` commit.

**Comment by alexgibson** [comment]
In Chrome I don't see any padding between the podcast graphic and the episode content (looks fine in Firefox and Safari)

<img width="841" alt="screen shot 2017-06-16 at 2 22 24 pm" src="https://user-images.githubusercontent.com/400117/27228392-5295e4da-529f-11e7-9a7a-b5fd2fa6401c.png">

**Comment by alexgibson** [comment]
Not a blocker for launch, but in Safari it's impossible to click the bottom menu bar unless I click twice (due to the way Safari hides it's own bottom menu on scroll)

![img_0466](https://user-images.githubusercontent.com/400117/27228518-da32e3f2-529f-11e7-9ad3-468b41deb4ad.PNG)

**Comment by alexgibson** [comment]
I seem to get a warning in FF saying the RSS feed content is not secure

<img width="379" alt="screen shot 2017-06-16 at 2 28 08 pm" src="https://user-images.githubusercontent.com/400117/27228567-0e1ed8ce-52a0-11e7-8fa2-8789c755b78e.png">

**Comment by alexgibson** [comment]
Is this well supported? (will it throw an error in some browsers) https://github.com/mozilla/irlpodcast/blob/master/assets/js/main.js#L17

**Comment by alexgibson** [comment]
Again not a blocker, but would be great if this repo included some linting tools for JS/CSS, also .editorconfig?

**Comment by alexgibson** [comment]
Remember to do this! https://github.com/mozilla/irlpodcast/blob/master/_includes/head.html#L12-L13

**Comment by alexgibson** [comment]
Site LGTM overall - tested most things in Firefox/Chrome/Safari, plus on mobile using iOS and looks good. As for commit history, I probably worry about squasing? At least now you can see how things came together :)

**Comment by alexgibson** [comment]
Looks like there is a 404 on the GTM snippet:

<img width="959" alt="screen shot 2017-06-16 at 3 01 34 pm" src="https://user-images.githubusercontent.com/400117/27229784-d03399be-52a4-11e7-82da-5d3065665e76.png">

**Comment by metadave** [comment]
@alexgibson the insecure RSS warning may be related to using this image w/ http:

http://media.simplecast.com/podcast/image/3077/1496878946-artwork.jpg

**Comment by alexgibson** [comment]
Nit: `&amp;` on iTunes links https://github.com/mozilla/irlpodcast/blob/master/_includes/head.html#L18

**Comment by alexgibson** [comment]
Should this be in an IIFE? https://github.com/mozilla/irlpodcast/blob/master/_includes/google-analytics.html#L2

**Comment by jpetto** [comment]
> Is document.execCommand well supported? (will it throw an error in some browsers) https://github.com/mozilla/irlpodcast/blob/master/assets/js/main.js#L17

Surprisingly, it is [well supported](http://caniuse.com/#search=execCommand). It's also in a `try` block, so it should fail silently when unavailable.

**Comment by jpetto** [comment]
> Not a blocker for launch, but in Safari it's impossible to click the bottom menu bar unless I click twice (due to the way Safari hides it's own bottom menu on scroll)

Ugh, this is a huge bummer. I found the following fix:

```
body,
html {
    height: 100%;
    overflow-y: scroll;
    -webkit-overflow-scrolling: touch;
}
```

Which seems to work great...until the iOS smart banner shows up and pushes the fixed footer off screen. 🙄 

However, fixing the menu to the top seems to be fine. It also solves a UX issue we've found - that people are clicking that Mozilla wordmark expecting to be taken to the homepage, but instead are taken to mozilla.org. I'm going to see if Michaela/Christa have any issues fixing the menu to the top.

**Comment by jpetto** [comment]
> Is document.execCommand well supported? (will it throw an error in some browsers) https://github.com/mozilla/irlpodcast/blob/master/assets/js/main.js#L17

And even though this is supported on iOS Safari, it doesn't work as expected due to some security restrictions. [clipboard.js](https://clipboardjs.com/), however, does work, so I'm going to move to that lib.

**Comment by alexgibson** [comment]
```
body,
html {
    height: 100%;
    overflow-y: scroll;
    -webkit-overflow-scrolling: touch;
}
```

Fwiw, this will wreak havoc on many older Android mobile devices, and leave the site entirely un-scrollable :(

`-webkit-overflow-scrolling: touch;` is also a great source of weird bugs. On iOS 11 it will soon be no more, as overflow scrolling becomes the new standard behavior :)
