### ISSUE TITLE
Get IRL V2 (Hugo) live

### ISSUE THREAD

**Issue by jpetto** [mozilla/irlpodcast#57]
Current plan:

- [x] Move existing Jekyll code base to legacy branch
- [x] Commit Hugo site to master
- [x] Tag Hugo commit as V 2.0
- [x] Create new `Jenkinsfile` & `bin/*.sh` scripts
- [x] Test & verify stage deployment
- [x] Test & verify prod deployment

**Comment by jpetto** [comment]
For reference, here's the Hugo site: https://github.com/jpetto/irl-hugo

**Comment by jgmize** [comment]
https://github.com/mozilla/irlpodcast/issues/58#issuecomment-387282690

**Comment by jgmize** [comment]
@jpetto it looks like everything has been done except for tagging Hugo as v2.0, correct?

**Comment by jpetto** [comment]
Yep, I think so. I'll tag the Hugo commit as 2.0 shortly.
