### ISSUE TITLE
Seo: Links to prev/next episode

### ISSUE THREAD

**Issue by rraue** [mozilla/irlpodcast#82]
There should be links in every episode page to the next and previous episodes to higher engagement and crawability of the page.

**Comment by stephaniehobson** [comment]
@rraue What is important to include in these links from an SEO perspective? 
- Episode name? 
- Episode season and number? S
- "Next" or "Previous"?

**Comment by rraue** [comment]
Episode name would be perfect, and as its should be not just a service for crawlers but for users jumping to the next episode, if interesting.

**Comment by stephaniehobson** [comment]
Fixed in #123. Should push to production with the next episode on Monday.
