### ISSUE TITLE
Add documentation for dev, staging, and production

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/irlpodcast#90]
It'd be nice to document the answers to some of these questions:

- What are the dev and staging urls?
- How do we build to test future dated episodes?
- How do we push to production?

**Comment by jpetto** [comment]
Submitted #91 to add dev/stage/prod push instructions.

Been looking in to building future-dated posts, but so far no luck. This is potentially a limitation to the Docker image we're using. For now, we can put in an incorrect early date for testing locally/on dev. We need to trigger a push/build at publish time anyway to update prod, at which time we can set the correct publish date. (This is how deployments worked under Jekyll as well.)
